jobs:
  lint:
    environment: release
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "18"
      - run: npm ci
      - run: npm run lint
    timeout-minutes: 10
  release:
    environment: release
    name: Release
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
  test:
    environment: release
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "18"
      - run: npm ci
      - run: npm run test
        env:
          POSTGRES_DSN: postgres:postgres@localhost:5432
    timeout-minutes: 10
name: Lint, build and release
on:
  push:
    branches:
      - main
